# LLM model parameters
llms:
  api:
    model: "gpt-5.4-nano"
    base_url: "https://llm.inzhenerka-cloud.com/"
    timeout: 60
    max_output_tokens: 512
  ollama:
    model: "gemma3:1b"
    base_url: "http://localhost:11434/v1/"
    timeout: 60
    max_output_tokens: 512

# Various app-wide settings
app:
  log_level: "INFO"
